"""restructure products into seperate tables

Revision ID: 4eb020e484a4
Revises: 284ae1f54073
Create Date: 2024-10-16 17:47:36.964500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb020e484a4'
down_revision: Union[str, None] = '284ae1f54073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('average_shelf_life_days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_product_association',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('product_information_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_information_id'], ['product_information.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'product_information_id')
    )
    op.add_column('products', sa.Column('product_information_id', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('purchase_date', sa.DateTime(), nullable=False))
    op.alter_column('products', 'expiration_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'products', 'product_information', ['product_information_id'], ['id'])
    op.drop_column('products', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.alter_column('products', 'expiration_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('products', 'purchase_date')
    op.drop_column('products', 'product_information_id')
    op.drop_table('category_product_association')
    op.drop_table('product_information')
    op.drop_table('categories')
    # ### end Alembic commands ###
