"""added polls table

Revision ID: b0753bfd3742
Revises: 4eb020e484a4
Create Date: 2024-10-19 19:41:47.566974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0753bfd3742'
down_revision: Union[str, None] = '4eb020e484a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_polls')
    # ### end Alembic commands ###
